Add status link to header and docs
matter-labs/zksync-lite-docs pull request #28
Opened 2020-12-25 14:02 UTC by perekopskiy

2020-12-29 06:04 UTC, StanislavBreadless requested changes
The task was to add the link to the header and as a searchable section. 

The link to the header was added, but the status link is not searchable. i.e. it can not be searched in the search bar at the top of the page.

Probably add it somewhere in the `FAQ`?

2021-01-03 13:49 UTC, Vladyslav-Bochok approved these changes

2021-01-12 11:16 UTC, popzxc approved these changes

2021-01-12 11:16 UTC, merged

2021-01-12 11:16 UTC, StanislavBreadless approved these changes