fix: update network names
matter-labs/zksync-lite-docs pull request #323
Opened 2023-02-23 14:40 UTC by krofax

Change network names, replaced ropsten, and rinkeby with goerli.

2023-02-23 14:52 UTC, githubdoramon requested changes

2023-02-23 14:52 UTC, githubdoramon commented on docs/api/changelog/README.md
> -| Ropsten | 0.9.0          | 0.3.0    | 0.0.1-b1 | 0.0.1     |
Missing Goerli

2023-02-23 15:26 UTC, JackHamer09 requested changes

2023-02-23 15:26 UTC, JackHamer09 commented on docs/api/sdk/checkout/tutorial/README.md
> +// 'Goerli' is also supported
it should be lowercase since it's a key value

2023-02-23 15:26 UTC, JackHamer09 commented on docs/api/sdk/checkout/types/README.md
> +type EthereumNetwork = 'Goerli' | 'mainnet';
also should be lowercase

2023-02-23 15:26 UTC, JackHamer09 commented on docs/api/sdk/java/README.md
> -- [zkSync Rinkeby testnet](https://rinkeby.zksync.io)
We can maybe have a link to the wallet or block explorer?
https://lite.zksync.io?network=goerli / https://goerli.zkscan.io

2023-02-23 15:26 UTC, JackHamer09 commented on docs/api/sdk/java/tutorial/README.md
> +AsyncProvider provider = AsyncProvider.defaultProvider(ChainId.goerli);
Probably should start with an uppercase

2023-02-23 15:26 UTC, JackHamer09 commented on docs/api/sdk/js/README.md
> -- [zkSync Rinkeby testnet](https://rinkeby.zksync.io)
We can maybe have a link to the wallet or block explorer?
https://lite.zksync.io?network=goerli / https://goerli.zkscan.io

2023-02-23 15:26 UTC, JackHamer09 commented on docs/api/sdk/rust/README.md
> -- [zkSync Rinkeby testnet](https://rinkeby.zksync.io)
We can maybe have a link to the wallet or block explorer?
https://lite.zksync.io?network=goerli / https://goerli.zkscan.io

2023-02-23 15:26 UTC, JackHamer09 commented on docs/dev/events/README.md
>  stabilized and may change in the future.
Probably this text is not really up to date

2023-02-23 15:26 UTC, JackHamer09 commented on docs/maintenance/README.md
> -To not get bored in the meanwhile, try out the [demo on Rinkeby testnet](https://rinkeby.zksync.io).
we can have a link to the wallet here

2023-02-23 15:26 UTC, JackHamer09 commented on docs/userdocs/status/README.md
> +To users that everything is working fine or that there are problems with a particular
Was this removed by accident?

2023-02-23 15:26 UTC, JackHamer09 commented on drafts/user/README.md
> +- zksync.io (goerli for testnet)
This looks weird
Is the paragraph talking about the wallet?

2023-02-23 15:39 UTC, krofax commented on docs/dev/events/README.md
>  stabilized and may change in the future.
@JackHamer09 what would you suggest it is?

2023-02-23 16:13 UTC, githubdoramon submitted a review, later dismissed

2023-02-24 08:59 UTC, JackHamer09 commented on docs/dev/events/README.md
>  stabilized and may change in the future.
I mean it says that API is not yet stabilized which isn't true anymore I think.

2023-02-24 16:55 UTC, JackHamer09 requested changes

2023-02-24 16:55 UTC, JackHamer09 commented on docs/api/sdk/swift/README.md
> +- [zkSync Lite block explorer](https://goerli.zkscan.io/)
Probably we want mainnet block explorer here?

2023-02-24 16:55 UTC, JackHamer09 commented on drafts/user/README.md
> +- zksync Lite [Block Explorer](https://goerli.zkscan.io/)
Probably we want mainnet block explorer here?

2023-02-24 16:55 UTC, JackHamer09 commented on drafts/user/README.md
> +- https://goerli.zkscan.io/
Probably we want mainnet block explorer here?

2023-02-24 16:55 UTC, JackHamer09 commented on docs/README.md
> +- **Block Explorer** (Everything you need to explore all transactions and blocks on zkSync). [Block Explorer](https://goerli.zkscan.io/)
Probably we want mainnet block explorer here?

2023-02-24 16:55 UTC, JackHamer09 commented on docs/README.md
> +- **Block Explorer** (Everything you need to explore all transactions and blocks on zkSync). [Block Explorer](https://goerli.zkscan.io/)
Also it's already said block explorer so maybe we can leave the link text to be zkscan.io, what do you think?

2023-02-24 16:55 UTC, JackHamer09 commented on docs/api/sdk/js/README.md
> +- [zkSync Lite Block Explorer](https://goerli.zkscan.io/)
Probably we want mainnet block explorer here?

2023-02-24 16:55 UTC, JackHamer09 commented on docs/api/sdk/python/README.md
> +- [zkSync Lite block explorer](https://goerli.zkscan.io/)
Probably we want mainnet block explorer here?

2023-02-24 16:55 UTC, JackHamer09 commented on docs/api/sdk/java/README.md
> +- [zkSync Lite Block Explorer](https://goerli.zkscan.io/)
Probably we want mainnet block explorer here?

2023-02-24 17:18 UTC, JackHamer09 approved these changes

2023-02-24 17:30 UTC, merged