(WIP) FAQ revision before public announcement
matter-labs/zksync-lite-docs pull request #45
Opened 2021-02-16 16:00 UTC by barakshani

2021-02-18 16:39 UTC, gluk64 requested changes

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/README.md
> +- Funds are as secure as in Ethereum mainnet
I feel we need to be more rigorous with this statement everywhere. Security is comparable to putting funds in a smart contract — if it has bugs, you can loose it, but if it doesn't, no game-theoretical tricks can get them out of there. I don't know how to formulate better, please suggest ideas. (This is also important for landings and other materials).

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/README.md
> +- Extremely low transaction fees
Periods at the end of each sentence of bullet points? For consistency.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/README.md
> +- Extremely low transaction fees
Or none nowhere.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/README.md
>  Get started by reading [the overview](/faq/intro.md).
I would out this last as a CTA, maybe even highlight, because FAQ opens collapsed and it's a bit hard to navigate.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/decentralization.md
> +their funds to Ethereum mainnet without any cooperation from operators (even if the latter is completely shut down and
operator => validator everywhere

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/decentralization.md
> +foundation registered under RSIN 861038204 in Kingsfordweg 151, 1043GR Amsterdam. The service operates at break-even
"close to break-even costs"? We're actually making some small profit, need to be honest about it.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/intro.md
>  - Zero-cost account creation.
It's actually not zero-cost: you pay 3x the normal fee for a transfer to a new account, and then you need to pay 11k gas to start using it. Let's rephrase: no registration is required to receive funds.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/intro.md
> +- Ultra-low transaction fees (~\$0.001 per transfer).
We're not as low, but at ~1/100th of mainnet costs for ERC20 tokens (1/30th for ETH transfers).

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/intro.md
> +- Withdrawals to mainnet in under 15 minutes.
Will be in the future, right now it takes hours to fill the blocks.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/intro.md
> +doesn't require any operational activity to keep the funds safe. For example, users can go offline for a year, then come
This will be the case once we have upgrades with strict opt-in. Until then, users still need to monitor the chain for upgrades, and withdraw if they disagree with the upcoming changes. We need to clarify this, but still keep the example because it shows where we're heading.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/roadmap.md
> +- Launch [token](/faq/tokenomics.md).
Launch zkSync governance token.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/security.md
> +- Users can always withdraw their assets onto the mainnet, regardless of cooperation from zkSync operators.
Some users were asking how can they withdraw in times when our service is down. They can't, must wait, that's why it says eventually. But maybe there is a better way to express this.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tech.md
> +the actual transaction throughput has an upper bound of 300 TPS due to the current limitations of the PLONK CRS. Yet,
Now 2000 TPS, after the recent upgrade. Not limited by PLONK anymore, only by ETH block gas limit to publish state delta upgrades. Yay!

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tech.md
> +difficulties such as the need for cycles of elliptic curves)! We already implemented, verified, and benchmarked it.
Live in production.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tech.md
> +accepted by the smart contract. The proof time generation is expected to be about 10 minutes, i.e. 10 minutes after
Need to explain that we wait for blocks to be filled now, which can take longer (hours).

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tech.md
> +accepted by the smart contract. The proof time generation is expected to be about 10 minutes, i.e. 10 minutes after
With the higher throughput we'll go down to minutes.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tokenomics.md
> +This has not been determined yet. Stay tuned.
Here we need to give them some CTA. Participate in the community, follow us everywhere, subscribe, join the company.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tokenomics.md
> +As stated [here](/faq/decentralization.md#how-decentralized-is-zksync), zkSync will become fully decentralized. The
Also mention a governance function.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/tokens.md
>  ## Listing a token
Will be permissionless after the next upgrade, already planned.

2021-02-18 16:39 UTC, gluk64 commented on docs/faq/wallets.md
> +Unlocking your account incur higher costs than other zkSync transactions, because the process of registration happens
11k gas for normal Ethereum keypair accounts — prob worth mentioning.

2021-02-18 16:46 UTC, barakshani commented on docs/faq/README.md
> +- Funds are as secure as in Ethereum mainnet
I agree. I actually had (and still have) some real trouble here, because it is not only game theory, we also use different cryptographic assumptions than Ethereum (like pairing) -- we do explain it under the Cryptography section.

Bottom line, we should be more formal and this should be modified.

2021-02-18 16:49 UTC, barakshani commented on docs/faq/README.md
> +- Funds are as secure as in Ethereum mainnet
Anyway, I will think further about it.

Bugs, as opposed to design flaws, less worry me -- it is part of the game. If we feel confident in our design, we should have no problems with statements like this. Bugs are on a different level, and can be fixed.

2021-02-19 20:23 UTC, barakshani commented on docs/faq/intro.md
> +![L2 comparison](https://zksync.io/chart4.png)
Need to make sure we see this image, once it is uploaded to thus url

2021-02-19 20:26 UTC, merged