Copyedit text
matter-labs/zksync-lite-docs pull request #64
Opened 2021-03-17 20:54 UTC by an-price

## Description
I have checked the smart contract documentation and the Rust SDK tutorial for consistent style and correct spelling, grammar, punctuation, and usage, and made corrections.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-03-17 21:01 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
>  let ethereum = wallet.ethereum(web3_address).await?
Should there be a semicolon at the end of line 116?

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +To interact with the Sync network, users need to know the endpoint of the operator node.
"Sync" -> "zkSync"

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +In this tutorial, we will demonstrate how to:
a comma suggests the reader to take a small pause - not really needed here.

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +- `signer_type`: Whether the signer adds the `\x19Ethereum...` prefix to signed messages. If `None`, the signer type will be deduced
"Indicates whether..."

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +// Generate from both a zkSync and an Ethereum private key.
Previous form seems correct (at least sounds better to me): you generate from both keys.

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +Using both the `WalletCredentials` and `Provider` objects, you can create a wallet:
The fixed sentence just says something else, but I agree that "once both" doesn't sounds good.
I'd write: "Once the objects `WalletCredentials` and `Provider` are created, you can create a wallet:"

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
>  let ethereum = wallet.ethereum(web3_address).await?
Yes, good catch

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +"ETH" stands for native ether. To transfer a supported ERC20 token, use the ERC20 address or ERC20 symbol instead of "ETH".
Ether is correct, similar to Dollar.

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +To control assets in the zkSync network, an account must register a public key once.
"an account must register its public key."

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +We are going to transfer `0.5 ETH` to another account. The fee will be set automatically to the least possible fee
"The fee will be set automatically by the server to the minimal acceptable amount."

2021-03-22 12:10 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +Note that the SDK may round the transferred amount or the fee down to the closest supported amount because the precision of transfers in
"may round down..."

2021-03-22 12:10 UTC, barakshani commented on docs/dev/contracts/README.md
> +atomic regardless of the number of contract instances involved.
I would keep the comma after "atomic" to make a short pause, as this sentence is quite complex and not so easy to follow.

2021-03-22 12:10 UTC, barakshani commented on docs/dev/contracts/README.md
> +Both the Zinc and Solidity languages will be supported at launch.
This sentence sounds quite odd (to my ear). Is it "both languages" or "both the languages"?

It might be better to write "Both Zinc and Solidity will be..." or "Zinc and Solidity will be both supported...".

2021-03-24 11:34 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
>  let ethereum = wallet.ethereum(web3_address).await?
I have pushed a change adding the semicolon.

2021-03-24 11:34 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +To interact with the Sync network, users need to know the endpoint of the operator node.
I have pushed a change replacing "Sync" with "zkSync".

2021-03-24 11:38 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +In this tutorial, we will demonstrate how to:
While commas can create a pause in a sentence, they also separate sentence elements. For example, an introductory adverbial phrase can be set off with a comma. On line 3 this phrase is short, so a comma isn't necessary, but I suggested the comma for consistency with line 39, where an even shorter introductory adverbial phrase is followed by a comma. If you prefer no comma after "tutorial" on line 3, then I recommend also deleting the comma after "default" on line 39.

2021-03-24 11:39 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +- `signer_type`: Whether the signer adds the `\x19Ethereum...` prefix to signed messages. If `None`, the signer type will be deduced
I have pushed a change replacing "Whether" with "Indicates whether".

2021-03-24 11:41 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +// Generate from both a zkSync and an Ethereum private key.
On its own, the original sentence does not make clear how many zkSync keys and how many Ethereum keys are used to generate the credentials. The revised sentence makes clear that exactly one zkSync key and exactly one Ethereum key are used; that is, a total of two keys are used.

2021-03-24 11:43 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +Using both the `WalletCredentials` and `Provider` objects, you can create a wallet:
I thought "once both" was OK; I reworded the sentence to avoid overusing "create".

Regarding your revised sentence, the phrase "the WalletCredentials and Provider objects" sounds more natural as noun adjuncts generally come before the nouns they modify.

2021-03-24 11:46 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +"ETH" stands for native ether. To transfer a supported ERC20 token, use the ERC20 address or ERC20 symbol instead of "ETH".
Yes, "ether" is like "dollar," which is also not capitalized. For example, see the dictionary by Merriam-Webster: www.merriam-webster.com/dictionary/dollar .

2021-03-24 11:47 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +To control assets in the zkSync network, an account must register a public key once.
I have pushed a change with your suggested wording.

2021-03-24 11:48 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +We are going to transfer `0.5 ETH` to another account. The fee will be set automatically to the least possible fee
I have pushed a change with your suggested wording.

2021-03-24 11:49 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +Note that the SDK may round the transferred amount or the fee down to the closest supported amount because the precision of transfers in
I have pushed a change with your suggested wording.

2021-03-24 11:49 UTC, an-price commented on docs/dev/contracts/README.md
> +atomic regardless of the number of contract instances involved.
I have pushed a change including the comma after "atomic".

2021-03-24 11:54 UTC, an-price commented on docs/dev/contracts/README.md
> +Both the Zinc and Solidity languages will be supported at launch.
I suggested adding "the" before "Zinc" because the words "Zinc" and "Solidity" indicate that we are talking about two particular languages. The languages are connected by the linking expression "both ... and".

You can write "both languages" and "both the languages". I prefer "both languages" because it is shorter.

Your revision is more concise than the original and I have pushed a change including it.

2021-03-24 13:41 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +Using both the `WalletCredentials` and `Provider` objects, you can create a wallet:
How about "are set" instead of "are created"?

2021-03-25 12:18 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +Using both the `WalletCredentials` and `Provider` objects, you can create a wallet:
I have pushed a change using the words "once" and "set".

2021-03-25 12:24 UTC, an-price commented
I've corrected a typo in some of my commit messages.

2021-03-26 09:55 UTC, barakshani approved these changes
Thanks for going over it and for the detailed explanation

2021-03-26 18:27 UTC, StanislavBreadless requested changes
Hi @an-price! That is a really nice job 👍 

There are a few points to address and we are good to go

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/api/sdk/rust/tutorial.md
> +The Ethereum signer is represented by the `EthereumSigner` trait from the `zksync_eth_signer` crate.
I am not sure whether should we use `An` (line 33) or `The`?

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/api/sdk/rust/tutorial.md
> +## Choosing an Ethereum signer
Why choosing? We instantiate it.

Maybe it would be better to just call it the "Ethereum Signer" (both start with capital)?

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/api/sdk/rust/tutorial.md
> +## Checking a zkSync account balance
Maybe use "a zkSync account's balance"?

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/api/sdk/rust/tutorial.md
> +We are going to transfer `0.5 ETH` to another account. The fee will be set automatically by the server to the minimal
The old version was more precise, because server does not automatically set the fee to be the lowest one.

Behind the scenes when the user sends the transaction the object queries the server for the minimal required amount and sets it for the transfer. So its not the server who sets the fee. We ask the server for the fee and then set what the server tells us.

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/dev/contracts/README.md
> +Both the Zinc and Solidity languages are Turing complete, so you can use unbounded loops, recursion, vectors and maps of
I don't think there is a need for "the" here. Both Zinc and Solidity are programming languages. 

An example of such grammar can be found here: http://www.math-cs.gordon.edu/courses/cps212/paperwork/Java-C++comparison.pdf on page 30 there is a sentence that begins with "In both Java and C++".

And it is also how it is written in the last line of the diff

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/dev/contracts/README.md
> +Zinc is created to fill the gap between these two worlds by providing a simple, reliable smart contract language that is optimized for ZKP circuits and easy for
Maybe "and is easy for developers to learn"?

2021-03-26 18:27 UTC, StanislavBreadless commented on docs/dev/contracts/README.md
> +The framework includes a simple, Turing complete, safety-focused, general purpose language designed specifically for
Hyphen is needed in general-purpose:
https://www.merriam-webster.com/dictionary/general-purpose#:~:text=%3A%20suitable%20to%20be%20used%20for%20two%20or%20more%20basic%20purposes

2021-03-26 19:29 UTC, barakshani commented on docs/api/sdk/rust/tutorial.md
> +We are going to transfer `0.5 ETH` to another account. The fee will be set automatically by the server to the minimal
My bad here - I suggested the new form.

2021-03-30 11:18 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +The Ethereum signer is represented by the `EthereumSigner` trait from the `zksync_eth_signer` crate.
I suggest "an" before "Ethereum signer" on line 33 because Ethereum signers are being mentioned for the first time.

2021-03-30 11:20 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +## Choosing an Ethereum signer
The advantage of a heading like "Instantiating an Ethereum signer" is that all the headings on this page then have parallel structure; they are all gerund phrases. If grammatical parallelism among same-level headings is unimportant, then the heading "Ethereum signer" is acceptable, using sentence-style capitalization for consistency with the other headings.

2021-03-30 11:21 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +## Checking a zkSync account balance
I have pushed a change with your suggested wording.

2021-03-30 11:21 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +We are going to transfer `0.5 ETH` to another account. The fee will be set automatically by the server to the minimal
I have pushed a change updating the wording according to your comments.

2021-03-30 11:22 UTC, an-price commented on docs/dev/contracts/README.md
> +Both the Zinc and Solidity languages are Turing complete, so you can use unbounded loops, recursion, vectors and maps of
Without the word "languages" after "Solidity", we could write "Both Zinc and Solidity" without the "the", like in the examples you gave. But when the word "languages" follows "Solidity", we need to use the definite article because we are talking about two particular languages, called Zinc and Solidity.

2021-03-30 11:24 UTC, an-price commented on docs/dev/contracts/README.md
> +Zinc is created to fill the gap between these two worlds by providing a simple, reliable smart contract language that is optimized for ZKP circuits and easy for
I have pushed a change with your suggested wording.

2021-03-30 11:24 UTC, an-price commented on docs/dev/contracts/README.md
> +The framework includes a simple, Turing complete, safety-focused, general purpose language designed specifically for
Thanks for pointing out that dictionary entry. I have pushed a change reinserting the hyphen.

2021-03-30 11:25 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +## Choosing an Ethereum signer
Please let me know which heading you prefer.

2021-03-31 14:43 UTC, StanislavBreadless commented on docs/api/sdk/rust/tutorial.md
> +## Choosing an Ethereum signer
I agree that "Instantiating an Ethereum signer" is better for consistency

2021-03-31 16:25 UTC, an-price commented on docs/api/sdk/rust/tutorial.md
> +## Choosing an Ethereum signer
I have pushed a change replacing the heading with "Instantiating an Ethereum signer.

2021-04-01 05:26 UTC, StanislavBreadless approved these changes
Fabulous!

2021-04-05 12:09 UTC, merged