Landing new review item + ui fixes
matter-labs/zksync-lite-docs pull request #65
Opened 2021-03-19 18:18 UTC by keriat

UI fixes, improvements & the new review we've agreed w/t Alex late yesterday.

2021-03-19 22:13 UTC, keriat reviewed
Couple generic advices:
@JackHamer09 

- [ ] get used to receive detailed reviews for small or huge change.

- [ ] Validate everything and automate any routine done for the 4th time. It save you time and do the impact on quality

- [x] We've already discussed the automation as only way to survive. Product is the marathon not a series of sprints. That's why we've spent time to configure linking and auto fix in your VS Code. Use it! Run the lint-css command, bet you'll be surprised 😉

2021-03-19 22:13 UTC, keriat commented on src/assets/style/blocks/_reviewsSlider.scss
> +      //display: none;
Don't leave any commented code. If needed we can roll-back or restore each and every state. There is a git for that.

2021-03-19 22:13 UTC, keriat commented on src/blocks/Header.vue
>                <a :href="'/dev/'" target="_blank" class="linkItem">Docs</a>
I do realize that is kinda out-of scope and you're not the one who was granted ownership on zksync.ui but this is tiny thing you should never left behind.

2021-03-19 22:13 UTC, keriat commented on src/blocks/Header.vue
>                    <i-dropdown-item href="https://zkscan.io/" target="_blank">zkScan</i-dropdown-item>
An advice: Since we have >10 products already listed inside zkProducts DB (and some more non-frontend like Atomic Swaps, zkPorter etc) it's a perfect moment to step in and replace it with the v-for iterator and a Collection ```Array<Object>```

Try always to be a couple steps ahead. Since it's the only stay actual

2021-03-19 22:13 UTC, keriat commented on src/blocks/Header.vue
>        opened: false,
I'm checking this PR from the phone, but I didn't find usage of the ```opened```. If  redundant it should be dropped.

2021-03-19 22:13 UTC, keriat commented on src/blocks/ReviewsSlider.vue
>            :key="singleReview.ref"
Let's drop either :key or :ref properties. Again, the phone may prevent me from 100% coverage but seems like it's a duplicate

2021-03-19 22:13 UTC, keriat commented on src/blocks/ReviewsSlider.vue
>            },
Again, it's not yours, but you should consider such things around. 
Export should be done the right way as intended while using TS: importing Vue object 
Also be verbose with the types, especially for complex base types like objects collection. It's time to define strict type for the review record

2021-03-21 23:23 UTC, JackHamer09 commented on src/blocks/ReviewsSlider.vue
>            :key="singleReview.ref"
key and ref are two completely different attributes and they are both required.
key is always required in v-for loop.
ref gives us the possibility to target the required block by the ref name.

2021-03-21 23:23 UTC, JackHamer09 commented on src/blocks/Header.vue
>        opened: false,
It is used to open the hamburger menu that is visible on <md breakpoint

2021-03-22 06:19 UTC, keriat reviewed
@JackHamer09 I've reviewed the code, for this time AOS error ignore is excepted, but in general we should avoid it.

And two more tweaks to finalize and publish this version:

- [ ] on mobile: set font-size: 12px for the first (new) review (see the gif-video: https://cln.sh/jHUNfr)
- [ ] on desktop: since there're more then 3 reviews, make the arrows visible: https://cln.sh/Nfuzez

2021-03-22 06:19 UTC, keriat commented on src/layouts/default.vue
> +// @ts-ignore: Unreachable code error
In general please avoid using such trade-off.
But in this particular case I can accept it since it's the landing, and AOS isn't built for TS.

2021-03-25 13:00 UTC, StanislavBreadless requested changes

2021-03-25 13:00 UTC, StanislavBreadless commented on src/blocks/Header.vue
> +          name: "zkWithdraw",
Alternative withdraw

2021-03-25 14:56 UTC, keriat commented on src/blocks/Header.vue
> +          name: "zkWithdraw",
Done by commit #43b35d3

2021-03-25 15:03 UTC, popzxc commented on src/components/Partners.vue
> +interface parenerDataItem {
Shouldn't interface names be in UpperCamelCase?

2021-03-25 15:03 UTC, popzxc commented on src/components/Partners.vue
> +interface parenerDataItem {
Also, it should be `Partner`, not `parener`.

2021-03-25 15:03 UTC, popzxc commented on src/layouts/default.vue
> +// @ts-ignore: Unreachable code error
Even if it's required, I strongly suggest adding a comment on why it's disabled and what should be done to remove it. Otherwise, it may get stuck here forever because developers will think "Probably there is a reason for that, I won't touch it just in case".

2021-03-25 15:03 UTC, popzxc commented on src/layouts/default.vue
> +    (this as any).$inkline.config.variant = "dark";
What's the point of `this as any`? Isn't it possible to use a real type here?

2021-03-25 15:12 UTC, JackHamer09 commented on src/layouts/default.vue
> +    (this as any).$inkline.config.variant = "dark";
> What's the point of `this as any`? Isn't it possible to use a real type here?

TS is not fully supported in Vue 2, therefore custom global properties are not visible. Inkline also doesn't support TS, so there are no types for it.

2021-03-25 15:12 UTC, keriat reviewed
@JackHamer09 Take a look on a couple of things mentioned.

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
> +      <div v-if="currentItem<(totalItems-1) && displayRightArrow" class="arrow right" @click="scrollItem('plus')">
Complex condition should be moved to the computed property @JackHamer09

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
>        if (this.$refs.container) {
This condition can be simplified.

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
>        }
Too much folded conditions. Need to be simplified.

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
> +    scrollItem(direction: "plus" | "minus") {
Better to split this method into two ```scrollItemBack``` and ```scrollItemForward```

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
> +        this.currentItem = Math.min(scrollTo, (this.$refs.reviewItem as HTMLElement[]).length - inViewNow);
Current item should be moved to the computed property since it is used more then once within the code in one *.vue file.

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
>      itemsInView() {
This seems to be a computed property, not method — let's move it there.

2021-03-25 15:12 UTC, keriat commented on src/blocks/ReviewsSlider.vue
> +    getAssetUrl(img: string) {
This one can be used as a filter (see https://ru.vuejs.org/v2/guide/filters.html for the details)

2021-03-25 15:16 UTC, popzxc commented on src/layouts/default.vue
> +    (this as any).$inkline.config.variant = "dark";
I see. May be worth a comment as well. Generally, if the line of code may raise a question, it's usually a good idea to have a comment with an answer to that question. Just to be sure that it won't be interpreted incorrectly.

2021-03-25 15:17 UTC, keriat commented on src/layouts/default.vue
> +    (this as any).$inkline.config.variant = "dark";
@JackHamer09 Let's avoid usage of $inkline configuration in vue. We can set this value in NuxtJs Config and remove if from the due code (I've done this for hmm, checkout).

2021-03-25 15:23 UTC, JackHamer09 commented on src/blocks/ReviewsSlider.vue
>      itemsInView() {
We can't move it to computed because there are too many conditions, it would significantly affect the performance to compute this property every time we call it and also we check for how many DOM elements are in the view, which is obviously not reactive.

2021-03-25 15:23 UTC, JackHamer09 commented on src/blocks/ReviewsSlider.vue
> +        this.currentItem = Math.min(scrollTo, (this.$refs.reviewItem as HTMLElement[]).length - inViewNow);
We can't move it to computed because there are too many conditions, it would significantly affect the performance to compute this property every time we call it and also we check for how many DOM elements are in the view, which is obviously not reactive.

2021-03-25 16:11 UTC, popzxc commented on docs/dev/contracts/README.md
> +State-of-the-art optimizations are applied to smart contract bytecode, whilst the virtual machine itself is optimized for high-load, allowing executing transactions in a blink of
The formatting seems broken.

2021-03-25 16:28 UTC, JackHamer09 commented on src/blocks/ReviewsSlider.vue
> +    getAssetUrl(img: string) {
It is not a good practice, because filters are being recalculated when on any Vue instance update (in this case it is cards scrolling, which could update Vue instance hundred times a second)

2021-03-25 16:32 UTC, merged